### ISSUE TITLE
Implement Image Drag N Drop

### ISSUE THREAD

**Issue by javalosr2004** [javalosr2004/personal_website_example#2]
# A simple to use drag n drop component for images, instead of having to create a string array.

- One example of a library is [react-dropzone](https://react-dropzone.js.org/)

## Uploading images

- Some common image hosting api's include [imgbb](https://api.imgbb.com/) and [cloudinary](https://console.cloudinary.com/)

**Comment by AtulPatidar1709** [comment]
👋 @javalosr2004, I want to work on this Issue can you please assist it to me.
