### ISSUE TITLE
Implement Form Validation

### ISSUE THREAD

**Issue by javalosr2004** [javalosr2004/personal_website_example#3]

**Comment by AtulPatidar1709** [comment]
Hello 👋 @javalosr2004 , I want to work on this form validation Implementation, can you please assign it to me.

**Comment by javalosr2004** [comment]
Hi @AtulPatidar1709, while I would love to assign this issue to you, the form itself is incomplete and I need time to set up credential so that you can securely use the database. Thank you for offering, I will reach out in a couple of day!
